# 使用最小化的Nixpacks配置
[phases.setup]
nixPkgs = [
  "python310",
  "postgresql_14"
]

[phases.install]
aptPkgs = ["nodejs", "npm"]
cmds = [
  "npm install -g yarn && YARN_PATH=$(npm bin -g)/yarn && cd web && $YARN_PATH install",
  "pip install psycopg2-binary"
]

[phases.build]
cmds = [
  "chmod +x start-services.sh",
  "chmod +x health-check.sh",
  "chmod +x railway-test.sh",
  "./railway-test.sh > railway-test-output.log || true",
  "YARN_PATH=$(npm bin -g)/yarn && cd web && $YARN_PATH NEXT_TELEMETRY_DISABLED=1 build:railway",
  "chmod +x setup-railway.sh && ./setup-railway.sh"
]

[start]
cmd = "sh ./start-services.sh"

[env]
PORT = "8080" 