[phases.setup]
nixPkgs = ["nodejs", "yarn", "python310"]

[phases.install]
cmds = [
  # 安装后端依赖
  "cd backend && python -m pip install --upgrade pip && pip install -r requirements.txt",
  # 安装前端依赖
  "cd web && yarn install"
]

[phases.build]
cmds = [
  # 构建前端
  "cd web && yarn build",
  # 设置Railway环境
  "chmod +x setup-railway.sh && ./setup-railway.sh",
  # 确保启动脚本可执行
  "chmod +x start-services.sh"
]

[start]
cmd = "sh ./start-services.sh"

[env]
PORT = "8080" 