[phases.setup]
nixPkgs = [
  "python310",
  "postgresql_14"
]
provideOutPaths = true

[phases.install]
cmds = [
  # 使用npx安装yarn
  "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash",
  "export NVM_DIR=\"$HOME/.nvm\" && [ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"",
  "nvm install 18 && nvm use 18",
  "npm install -g yarn",
  # 安装前端依赖
  "cd web && yarn install"
]

[phases.build]
cmds = [
  # 确保脚本可执行
  "chmod +x start-services.sh",
  "chmod +x health-check.sh",
  "chmod +x railway-test.sh",
  # 运行诊断脚本
  "./railway-test.sh > railway-test-output.log || true",
  # 构建前端 - 使用自定义脚本跳过类型检查
  "cd web && NEXT_TELEMETRY_DISABLED=1 yarn build:railway",
  # 设置Railway环境
  "chmod +x setup-railway.sh && ./setup-railway.sh"
]

[phases.cleanup]
cmds = [
  "rm -rf ~/.npm",
  "rm -f /nix/var/nix/profiles/per-user/*/share/bash-completion/completions/npm || true"
]

[start]
cmd = "sh ./start-services.sh"

[env]
PORT = "8080" 