# 使用最小化的Nixpacks配置
[phases.setup]
nixpkgs = ["nodejs_20", "yarn", "nodePackages.prisma"]

[phases.install]
aptPkgs = ["nodejs", "npm", "python3", "python3-pip", "python3-dev", "build-essential", "libpq-dev"]
cmds = [
  # 确保系统PATH优先于Nix PATH
  "export PATH=/usr/bin:/usr/local/bin:$PATH",
  "cd web && npm ci",
  "export PATH=/usr/bin:/usr/local/bin:$PATH && python3 -m pip install psycopg2-binary"
]

[phases.build]
cmds = [
  "export PATH=/usr/bin:/usr/local/bin:$PATH",
  "chmod +x start-services.sh",
  "chmod +x health-check.sh",
  "chmod +x railway-test.sh",
  "./railway-test.sh > railway-test-output.log || true",
  "cd web && npx prisma generate && npm run build",
  "chmod +x setup-railway.sh && ./setup-railway.sh"
]

[start]
cmd = "cd web && npm start"

[env]
PORT = "8080" 