[build]
builder = "nixpacks"
buildCommand = "echo 'Using nixpacks.toml configuration'"

[deploy]
startCommand = "sh ./start-services.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[deploy.web]
healthcheckPath = "/api/health"
restartPolicyType = "ON_FAILURE"

[deploy.backend]
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE" 