#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check api-cf code
echo "🔍 Checking api-cf code..."
cd api-cf

echo "💅 Formatting code..."
pnpm format

echo "🔍 Running ESLint..."
pnpm lint:fix

echo "📝 Type checking..."
pnpm exec tsc --noEmit

echo "✨ Running lint-staged..."
pnpm lint-staged

# Check web code
echo "\n🔍 Checking web code..."
cd ../web

echo "💅 Formatting code..."
pnpm format

echo "🔍 Running ESLint..."
pnpm lint:fix

echo "📝 Type checking..."
pnpm exec tsc --noEmit

echo "✨ Running lint-staged..."
pnpm lint-staged
